# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cart.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(982, 618)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(730, 550, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    font: 700 14pt \"Sitka\";\n"
"    color: white;\n"
"    background-color: rgb(0, 85, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.ProductFrame1 = QtWidgets.QFrame(self.centralwidget)
        self.ProductFrame1.setGeometry(QtCore.QRect(40, 140, 441, 111))
        self.ProductFrame1.setStyleSheet("QFrame {\n"
"    background: lightgray;\n"
"    border-radius: 30px;\n"
"}")
        self.ProductFrame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProductFrame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProductFrame1.setObjectName("ProductFrame1")
        self.DeleteButton1 = QtWidgets.QPushButton(self.ProductFrame1)
        self.DeleteButton1.setGeometry(QtCore.QRect(310, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DeleteButton1.setFont(font)
        self.DeleteButton1.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: red;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: darkred;\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.DeleteButton1.setObjectName("DeleteButton1")
        self.CartProductAmount1 = QtWidgets.QLabel(self.ProductFrame1)
        self.CartProductAmount1.setGeometry(QtCore.QRect(310, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductAmount1.setFont(font)
        self.CartProductAmount1.setAlignment(QtCore.Qt.AlignCenter)
        self.CartProductAmount1.setObjectName("CartProductAmount1")
        self.CartProductLabel1 = QtWidgets.QLabel(self.ProductFrame1)
        self.CartProductLabel1.setGeometry(QtCore.QRect(170, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductLabel1.setFont(font)
        self.CartProductLabel1.setText("")
        self.CartProductLabel1.setObjectName("CartProductLabel1")
        self.CartProductPicture1 = QtWidgets.QLabel(self.ProductFrame1)
        self.CartProductPicture1.setGeometry(QtCore.QRect(20, 10, 131, 91))
        self.CartProductPicture1.setStyleSheet("QLabel {\n"
"    image: url(:/)\n"
"}")
        self.CartProductPicture1.setText("")
        self.CartProductPicture1.setObjectName("CartProductPicture1")
        self.CartProductPrice1 = QtWidgets.QLabel(self.ProductFrame1)
        self.CartProductPrice1.setGeometry(QtCore.QRect(170, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductPrice1.setFont(font)
        self.CartProductPrice1.setText("")
        self.CartProductPrice1.setObjectName("CartProductPrice1")
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(60, 570, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.BackButton.setFont(font)
        self.BackButton.setStyleSheet("QPushButton {\n"
"font: 700 10pt \"Sitka\";\n"
"    color: white;\n"
"    background-color: rgb(0, 85, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.BackButton.setObjectName("BackButton")
        self.ReloadButton = QtWidgets.QPushButton(self.centralwidget)
        self.ReloadButton.setGeometry(QtCore.QRect(60, 530, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.ReloadButton.setFont(font)
        self.ReloadButton.setStyleSheet("QPushButton {\n"
"font: 700 8pt \"Sitka\";\n"
"color: white;\n"
"    background-color: rgb(0, 85, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: gray;\n"
"    background: lightblue;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.ReloadButton.setObjectName("ReloadButton")
        self.ProductFrame2 = QtWidgets.QFrame(self.centralwidget)
        self.ProductFrame2.setGeometry(QtCore.QRect(520, 140, 441, 111))
        self.ProductFrame2.setStyleSheet("QFrame {\n"
"    background: lightgray;\n"
"    border-radius: 30px;\n"
"}")
        self.ProductFrame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProductFrame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProductFrame2.setObjectName("ProductFrame2")
        self.DeleteButton2 = QtWidgets.QPushButton(self.ProductFrame2)
        self.DeleteButton2.setGeometry(QtCore.QRect(310, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DeleteButton2.setFont(font)
        self.DeleteButton2.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: red;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: darkred;\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.DeleteButton2.setObjectName("DeleteButton2")
        self.CartProductAmount2 = QtWidgets.QLabel(self.ProductFrame2)
        self.CartProductAmount2.setGeometry(QtCore.QRect(310, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductAmount2.setFont(font)
        self.CartProductAmount2.setAlignment(QtCore.Qt.AlignCenter)
        self.CartProductAmount2.setObjectName("CartProductAmount2")
        self.CartProductLabel2 = QtWidgets.QLabel(self.ProductFrame2)
        self.CartProductLabel2.setGeometry(QtCore.QRect(170, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductLabel2.setFont(font)
        self.CartProductLabel2.setText("")
        self.CartProductLabel2.setObjectName("CartProductLabel2")
        self.CartProductPicture2 = QtWidgets.QLabel(self.ProductFrame2)
        self.CartProductPicture2.setGeometry(QtCore.QRect(20, 10, 131, 91))
        self.CartProductPicture2.setStyleSheet("QLabel {\n"
"    image: url(:/)\n"
"}")
        self.CartProductPicture2.setText("")
        self.CartProductPicture2.setObjectName("CartProductPicture2")
        self.CartProductPrice2 = QtWidgets.QLabel(self.ProductFrame2)
        self.CartProductPrice2.setGeometry(QtCore.QRect(170, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductPrice2.setFont(font)
        self.CartProductPrice2.setText("")
        self.CartProductPrice2.setObjectName("CartProductPrice2")
        self.ProductFrame3 = QtWidgets.QFrame(self.centralwidget)
        self.ProductFrame3.setGeometry(QtCore.QRect(40, 270, 441, 111))
        self.ProductFrame3.setStyleSheet("QFrame {\n"
"    background: lightgray;\n"
"    border-radius: 30px;\n"
"}")
        self.ProductFrame3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProductFrame3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProductFrame3.setObjectName("ProductFrame3")
        self.DeleteButton3 = QtWidgets.QPushButton(self.ProductFrame3)
        self.DeleteButton3.setGeometry(QtCore.QRect(310, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DeleteButton3.setFont(font)
        self.DeleteButton3.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: red;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: darkred;\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.DeleteButton3.setObjectName("DeleteButton3")
        self.CartProductAmount3 = QtWidgets.QLabel(self.ProductFrame3)
        self.CartProductAmount3.setGeometry(QtCore.QRect(310, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductAmount3.setFont(font)
        self.CartProductAmount3.setAlignment(QtCore.Qt.AlignCenter)
        self.CartProductAmount3.setObjectName("CartProductAmount3")
        self.CartProductLabel3 = QtWidgets.QLabel(self.ProductFrame3)
        self.CartProductLabel3.setGeometry(QtCore.QRect(170, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductLabel3.setFont(font)
        self.CartProductLabel3.setText("")
        self.CartProductLabel3.setObjectName("CartProductLabel3")
        self.CartProductPicture3 = QtWidgets.QLabel(self.ProductFrame3)
        self.CartProductPicture3.setGeometry(QtCore.QRect(20, 10, 131, 91))
        self.CartProductPicture3.setStyleSheet("QLabel {\n"
"    image: url(:/)\n"
"}")
        self.CartProductPicture3.setText("")
        self.CartProductPicture3.setObjectName("CartProductPicture3")
        self.CartProductPrice3 = QtWidgets.QLabel(self.ProductFrame3)
        self.CartProductPrice3.setGeometry(QtCore.QRect(170, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductPrice3.setFont(font)
        self.CartProductPrice3.setText("")
        self.CartProductPrice3.setObjectName("CartProductPrice3")
        self.ProductFrame5 = QtWidgets.QFrame(self.centralwidget)
        self.ProductFrame5.setGeometry(QtCore.QRect(40, 400, 441, 111))
        self.ProductFrame5.setStyleSheet("QFrame {\n"
"    background: lightgray;\n"
"    border-radius: 30px;\n"
"}")
        self.ProductFrame5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProductFrame5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProductFrame5.setObjectName("ProductFrame5")
        self.DeleteButton5 = QtWidgets.QPushButton(self.ProductFrame5)
        self.DeleteButton5.setGeometry(QtCore.QRect(310, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DeleteButton5.setFont(font)
        self.DeleteButton5.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: red;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: darkred;\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.DeleteButton5.setObjectName("DeleteButton5")
        self.CartProductAmount5 = QtWidgets.QLabel(self.ProductFrame5)
        self.CartProductAmount5.setGeometry(QtCore.QRect(310, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductAmount5.setFont(font)
        self.CartProductAmount5.setAlignment(QtCore.Qt.AlignCenter)
        self.CartProductAmount5.setObjectName("CartProductAmount5")
        self.CartProductLabel5 = QtWidgets.QLabel(self.ProductFrame5)
        self.CartProductLabel5.setGeometry(QtCore.QRect(170, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductLabel5.setFont(font)
        self.CartProductLabel5.setText("")
        self.CartProductLabel5.setObjectName("CartProductLabel5")
        self.CartProductPicture5 = QtWidgets.QLabel(self.ProductFrame5)
        self.CartProductPicture5.setGeometry(QtCore.QRect(20, 10, 131, 91))
        self.CartProductPicture5.setStyleSheet("QLabel {\n"
"    image: url(:/)\n"
"}")
        self.CartProductPicture5.setText("")
        self.CartProductPicture5.setObjectName("CartProductPicture5")
        self.CartProductPrice5 = QtWidgets.QLabel(self.ProductFrame5)
        self.CartProductPrice5.setGeometry(QtCore.QRect(170, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductPrice5.setFont(font)
        self.CartProductPrice5.setText("")
        self.CartProductPrice5.setObjectName("CartProductPrice5")
        self.ProductFrame4 = QtWidgets.QFrame(self.centralwidget)
        self.ProductFrame4.setGeometry(QtCore.QRect(520, 270, 441, 111))
        self.ProductFrame4.setStyleSheet("QFrame {\n"
"    background: lightgray;\n"
"    border-radius: 30px;\n"
"}")
        self.ProductFrame4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProductFrame4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProductFrame4.setObjectName("ProductFrame4")
        self.DeleteButton4 = QtWidgets.QPushButton(self.ProductFrame4)
        self.DeleteButton4.setGeometry(QtCore.QRect(310, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DeleteButton4.setFont(font)
        self.DeleteButton4.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: red;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: darkred;\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.DeleteButton4.setObjectName("DeleteButton4")
        self.CartProductAmount4 = QtWidgets.QLabel(self.ProductFrame4)
        self.CartProductAmount4.setGeometry(QtCore.QRect(310, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductAmount4.setFont(font)
        self.CartProductAmount4.setAlignment(QtCore.Qt.AlignCenter)
        self.CartProductAmount4.setObjectName("CartProductAmount4")
        self.CartProductLabel4 = QtWidgets.QLabel(self.ProductFrame4)
        self.CartProductLabel4.setGeometry(QtCore.QRect(170, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductLabel4.setFont(font)
        self.CartProductLabel4.setText("")
        self.CartProductLabel4.setObjectName("CartProductLabel4")
        self.CartProductPicture4 = QtWidgets.QLabel(self.ProductFrame4)
        self.CartProductPicture4.setGeometry(QtCore.QRect(20, 10, 131, 91))
        self.CartProductPicture4.setStyleSheet("QLabel {\n"
"    image: url(:/)\n"
"}")
        self.CartProductPicture4.setText("")
        self.CartProductPicture4.setObjectName("CartProductPicture4")
        self.CartProductPrice4 = QtWidgets.QLabel(self.ProductFrame4)
        self.CartProductPrice4.setGeometry(QtCore.QRect(170, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductPrice4.setFont(font)
        self.CartProductPrice4.setText("")
        self.CartProductPrice4.setObjectName("CartProductPrice4")
        self.ProductFrame6 = QtWidgets.QFrame(self.centralwidget)
        self.ProductFrame6.setGeometry(QtCore.QRect(520, 400, 441, 111))
        self.ProductFrame6.setStyleSheet("QFrame {\n"
"    background: lightgray;\n"
"    border-radius: 30px;\n"
"}")
        self.ProductFrame6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ProductFrame6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProductFrame6.setObjectName("ProductFrame6")
        self.DeleteButton6 = QtWidgets.QPushButton(self.ProductFrame6)
        self.DeleteButton6.setGeometry(QtCore.QRect(310, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DeleteButton6.setFont(font)
        self.DeleteButton6.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background: red;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: darkred;\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"\n"
"")
        self.DeleteButton6.setObjectName("DeleteButton6")
        self.CartProductAmount6 = QtWidgets.QLabel(self.ProductFrame6)
        self.CartProductAmount6.setGeometry(QtCore.QRect(310, 40, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductAmount6.setFont(font)
        self.CartProductAmount6.setAlignment(QtCore.Qt.AlignCenter)
        self.CartProductAmount6.setObjectName("CartProductAmount6")
        self.CartProductLabel6 = QtWidgets.QLabel(self.ProductFrame6)
        self.CartProductLabel6.setGeometry(QtCore.QRect(170, 30, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductLabel6.setFont(font)
        self.CartProductLabel6.setText("")
        self.CartProductLabel6.setObjectName("CartProductLabel6")
        self.CartProductPicture6 = QtWidgets.QLabel(self.ProductFrame6)
        self.CartProductPicture6.setGeometry(QtCore.QRect(20, 10, 131, 91))
        self.CartProductPicture6.setStyleSheet("QLabel {\n"
"    image: url(:/)\n"
"}")
        self.CartProductPicture6.setText("")
        self.CartProductPicture6.setObjectName("CartProductPicture6")
        self.CartProductPrice6 = QtWidgets.QLabel(self.ProductFrame6)
        self.CartProductPrice6.setGeometry(QtCore.QRect(170, 80, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        self.CartProductPrice6.setFont(font)
        self.CartProductPrice6.setText("")
        self.CartProductPrice6.setObjectName("CartProductPrice6")
        self.LeftButton = QtWidgets.QPushButton(self.centralwidget)
        self.LeftButton.setGeometry(QtCore.QRect(390, 560, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.LeftButton.setFont(font)
        self.LeftButton.setStyleSheet("QPushButton {\n"
"font: 700 12pt \"Sitka\";\n"
"    background: white;\n"
"    border-radius: 20px;\n"
"    image: url(:/others/Arrow/leftArrow.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: lightgreen;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"\n"
"")
        self.LeftButton.setText("")
        self.LeftButton.setObjectName("LeftButton")
        self.RightButton = QtWidgets.QPushButton(self.centralwidget)
        self.RightButton.setGeometry(QtCore.QRect(570, 560, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium Cond")
        font.setPointSize(12)
        font.setBold(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.RightButton.setFont(font)
        self.RightButton.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border-radius: 20px;\n"
"    image: url(:/others/Arrow/rightArrow.png);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: lightgreen;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"\n"
"")
        self.RightButton.setText("")
        self.RightButton.setObjectName("RightButton")
        self.TotalLabel = QtWidgets.QLabel(self.centralwidget)
        self.TotalLabel.setGeometry(QtCore.QRect(750, 500, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.TotalLabel.setFont(font)
        self.TotalLabel.setStyleSheet("font: 700 12pt \"Sitka\";")
        self.TotalLabel.setObjectName("TotalLabel")
        self.PageLabel = QtWidgets.QLabel(self.centralwidget)
        self.PageLabel.setGeometry(QtCore.QRect(440, 570, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.PageLabel.setFont(font)
        self.PageLabel.setStyleSheet("font: 700 12pt \"Sitka\";")
        self.PageLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PageLabel.setObjectName("PageLabel")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1131, 691))
        self.label_2.setStyleSheet("background-image: url(:/Bg/Background.jpg);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Bg/Background.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 110, 1011, 731))
        self.graphicsView.setStyleSheet("QFrame {\n"
"    \n"
"    background-color: rgb(237, 236, 233);\n"
"    border-radius: 50px;\n"
"}")
        self.graphicsView.setObjectName("graphicsView")
        self.Label = QtWidgets.QLabel(self.centralwidget)
        self.Label.setGeometry(QtCore.QRect(70, 0, 851, 101))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(50)
        font.setBold(True)
        font.setItalic(True)
        self.Label.setFont(font)
        self.Label.setStyleSheet("QLabel {\n"
"    color: rgb(245, 245, 245);\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}")
        self.Label.setAlignment(QtCore.Qt.AlignCenter)
        self.Label.setObjectName("Label")
        self.label_2.raise_()
        self.graphicsView.raise_()
        self.pushButton_2.raise_()
        self.ProductFrame1.raise_()
        self.BackButton.raise_()
        self.ReloadButton.raise_()
        self.ProductFrame2.raise_()
        self.ProductFrame3.raise_()
        self.ProductFrame5.raise_()
        self.ProductFrame4.raise_()
        self.ProductFrame6.raise_()
        self.LeftButton.raise_()
        self.RightButton.raise_()
        self.TotalLabel.raise_()
        self.PageLabel.raise_()
        self.Label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "CHECK OUT"))
        self.DeleteButton1.setText(_translate("MainWindow", "Delete"))
        self.CartProductAmount1.setText(_translate("MainWindow", "Buy: 0"))
        self.BackButton.setText(_translate("MainWindow", "Go Back"))
        self.ReloadButton.setText(_translate("MainWindow", "Calculate Price"))
        self.DeleteButton2.setText(_translate("MainWindow", "Delete"))
        self.CartProductAmount2.setText(_translate("MainWindow", "Buy: 0"))
        self.DeleteButton3.setText(_translate("MainWindow", "Delete"))
        self.CartProductAmount3.setText(_translate("MainWindow", "Buy: 0"))
        self.DeleteButton5.setText(_translate("MainWindow", "Delete"))
        self.CartProductAmount5.setText(_translate("MainWindow", "Buy: 0"))
        self.DeleteButton4.setText(_translate("MainWindow", "Delete"))
        self.CartProductAmount4.setText(_translate("MainWindow", "Buy: 0"))
        self.DeleteButton6.setText(_translate("MainWindow", "Delete"))
        self.CartProductAmount6.setText(_translate("MainWindow", "Buy: 0"))
        self.TotalLabel.setText(_translate("MainWindow", "Total:"))
        self.PageLabel.setText(_translate("MainWindow", "Page: 1/1"))
        self.Label.setText(_translate("MainWindow", "Cart"))
import Bg_rc
import pic_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
