# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(660, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.PageLabel = QtWidgets.QLabel(self.centralwidget)
        self.PageLabel.setGeometry(QtCore.QRect(30, -10, 541, 81))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(True)
        self.PageLabel.setFont(font)
        self.PageLabel.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PageLabel.setObjectName("PageLabel")
        self.InfoLabel = QtWidgets.QLabel(self.centralwidget)
        self.InfoLabel.setGeometry(QtCore.QRect(30, 80, 421, 16))
        font = QtGui.QFont()
        font.setFamily("Franklin Gothic Medium")
        font.setPointSize(12)
        self.InfoLabel.setFont(font)
        self.InfoLabel.setStyleSheet("color: rgb(255, 255, 255);")
        self.InfoLabel.setObjectName("InfoLabel")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 110, 661, 321))
        self.frame.setStyleSheet("QFrame {\n"
"    background-color: rgb(237, 236, 233);\n"
"    border-radius: 50px;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.UsernameLabel = QtWidgets.QLabel(self.frame)
        self.UsernameLabel.setGeometry(QtCore.QRect(30, 20, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.UsernameLabel.setFont(font)
        self.UsernameLabel.setStyleSheet("font: 12pt \"Sitka Small\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.UsernameLabel.setObjectName("UsernameLabel")
        self.PasswordLabel = QtWidgets.QLabel(self.frame)
        self.PasswordLabel.setGeometry(QtCore.QRect(30, 70, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setStyleSheet("font: 12pt \"Sitka Small\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.RePasswordLabel = QtWidgets.QLabel(self.frame)
        self.RePasswordLabel.setGeometry(QtCore.QRect(30, 120, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        self.RePasswordLabel.setFont(font)
        self.RePasswordLabel.setStyleSheet("font: 12pt \"Sitka Small\";\n"
"background-color: rgba(255, 255, 255, 0);")
        self.RePasswordLabel.setObjectName("RePasswordLabel")
        self.UsernameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.UsernameLineEdit.setGeometry(QtCore.QRect(190, 20, 411, 31))
        self.UsernameLineEdit.setStyleSheet("    font: 13pt \"Sitka Small\";\n"
"    color: black;\n"
"    border-radius: 15px;")
        self.UsernameLineEdit.setObjectName("UsernameLineEdit")
        self.PasswordLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PasswordLineEdit.setGeometry(QtCore.QRect(190, 70, 411, 31))
        self.PasswordLineEdit.setStyleSheet("    font: 13pt \"Sitka Small\";\n"
"    color: black;\n"
"    border-radius: 15px;")
        self.PasswordLineEdit.setObjectName("PasswordLineEdit")
        self.RePasswordLineEdit = QtWidgets.QLineEdit(self.frame)
        self.RePasswordLineEdit.setGeometry(QtCore.QRect(190, 120, 411, 31))
        self.RePasswordLineEdit.setStyleSheet("    font: 13pt \"Sitka Small\";\n"
"    color: black;\n"
"    border-radius: 15px;")
        self.RePasswordLineEdit.setObjectName("RePasswordLineEdit")
        self.ConfirmButton = QtWidgets.QPushButton(self.frame)
        self.ConfirmButton.setGeometry(QtCore.QRect(250, 170, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        self.ConfirmButton.setFont(font)
        self.ConfirmButton.setStyleSheet("QPushButton {\n"
"    font: 15pt \"Sitka Small\";\n"
"    color: white;\n"
"    background-color: rgb(0, 85, 0);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}")
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(-10, -380, 921, 791))
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap(":/Bg/Background.jpg"))
        self.label_7.setScaledContents(True)
        self.label_7.setObjectName("label_7")
        self.label_7.raise_()
        self.PageLabel.raise_()
        self.InfoLabel.raise_()
        self.frame.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PageLabel.setText(_translate("MainWindow", "Register page"))
        self.InfoLabel.setText(_translate("MainWindow", "Please fill in below to register a new account."))
        self.UsernameLabel.setText(_translate("MainWindow", "Username"))
        self.PasswordLabel.setText(_translate("MainWindow", "Password"))
        self.RePasswordLabel.setText(_translate("MainWindow", "Re-Password"))
        self.ConfirmButton.setText(_translate("MainWindow", "CONFIRM"))
import Bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
