# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sell_product.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(646, 491)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ConfirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.ConfirmButton.setGeometry(QtCore.QRect(270, 430, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.ConfirmButton.setFont(font)
        self.ConfirmButton.setStyleSheet("QPushButton {\n"
"    background: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #64AB25;\n"
"    background: #333;\n"
"    border-radius: 15px;\n"
"}")
        self.ConfirmButton.setObjectName("ConfirmButton")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 100, 591, 311))
        self.frame.setStyleSheet("background-color: rgb(237, 236, 233);\n"
"border-radius: 50px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.NameLineEdit = QtWidgets.QLineEdit(self.frame)
        self.NameLineEdit.setGeometry(QtCore.QRect(190, 20, 371, 31))
        self.NameLineEdit.setStyleSheet("    font: 13pt \"Sitka Small\";\n"
"    border-radius: 15px;\n"
"background-color: rgb(255, 255, 255);")
        self.NameLineEdit.setObjectName("NameLineEdit")
        self.PriceLineEdit = QtWidgets.QLineEdit(self.frame)
        self.PriceLineEdit.setGeometry(QtCore.QRect(190, 70, 371, 31))
        self.PriceLineEdit.setStyleSheet("    font: 13pt \"Sitka Small\";\n"
"    \n"
"background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;")
        self.PriceLineEdit.setObjectName("PriceLineEdit")
        self.VegetableCategory = QtWidgets.QRadioButton(self.frame)
        self.VegetableCategory.setGeometry(QtCore.QRect(220, 119, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.VegetableCategory.setFont(font)
        self.VegetableCategory.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.VegetableCategory.setObjectName("VegetableCategory")
        self.FruitCategory = QtWidgets.QRadioButton(self.frame)
        self.FruitCategory.setGeometry(QtCore.QRect(430, 119, 89, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.FruitCategory.setFont(font)
        self.FruitCategory.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.FruitCategory.setObjectName("FruitCategory")
        self.DailyProductCategory = QtWidgets.QRadioButton(self.frame)
        self.DailyProductCategory.setGeometry(QtCore.QRect(220, 159, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.DailyProductCategory.setFont(font)
        self.DailyProductCategory.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.DailyProductCategory.setObjectName("DailyProductCategory")
        self.OTOPCategory = QtWidgets.QRadioButton(self.frame)
        self.OTOPCategory.setGeometry(QtCore.QRect(430, 159, 89, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(10)
        self.OTOPCategory.setFont(font)
        self.OTOPCategory.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.OTOPCategory.setObjectName("OTOPCategory")
        self.PriceLabel = QtWidgets.QLabel(self.frame)
        self.PriceLabel.setGeometry(QtCore.QRect(20, 70, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.PriceLabel.setFont(font)
        self.PriceLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.PriceLabel.setObjectName("PriceLabel")
        self.NameLabel = QtWidgets.QLabel(self.frame)
        self.NameLabel.setGeometry(QtCore.QRect(20, 20, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.NameLabel.setFont(font)
        self.NameLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.NameLabel.setObjectName("NameLabel")
        self.CategoryLabel = QtWidgets.QLabel(self.frame)
        self.CategoryLabel.setGeometry(QtCore.QRect(20, 120, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.CategoryLabel.setFont(font)
        self.CategoryLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.CategoryLabel.setObjectName("CategoryLabel")
        self.DetailTextEdit = QtWidgets.QTextEdit(self.frame)
        self.DetailTextEdit.setGeometry(QtCore.QRect(190, 210, 371, 71))
        self.DetailTextEdit.setStyleSheet("\n"
"font: 13pt \"Sitka Small\";\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 15px;")
        self.DetailTextEdit.setObjectName("DetailTextEdit")
        self.DetailLabel = QtWidgets.QLabel(self.frame)
        self.DetailLabel.setGeometry(QtCore.QRect(20, 210, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Sitka Small")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.DetailLabel.setFont(font)
        self.DetailLabel.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"")
        self.DetailLabel.setObjectName("DetailLabel")
        self.PageLabel = QtWidgets.QLabel(self.centralwidget)
        self.PageLabel.setGeometry(QtCore.QRect(30, 20, 581, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka")
        font.setPointSize(32)
        font.setBold(True)
        font.setItalic(True)
        self.PageLabel.setFont(font)
        self.PageLabel.setStyleSheet("color: white;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.PageLabel.setObjectName("PageLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-230, -120, 1071, 641))
        self.label.setStyleSheet("background-image: url(:/Bg/Background.jpg);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/Bg/Background.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.ConfirmButton.raise_()
        self.frame.raise_()
        self.PageLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ConfirmButton.setText(_translate("MainWindow", "Confirm"))
        self.VegetableCategory.setText(_translate("MainWindow", "Vegetable"))
        self.FruitCategory.setText(_translate("MainWindow", "Fruit"))
        self.DailyProductCategory.setText(_translate("MainWindow", "Daily product"))
        self.OTOPCategory.setText(_translate("MainWindow", "OTOP"))
        self.PriceLabel.setText(_translate("MainWindow", "Price"))
        self.NameLabel.setText(_translate("MainWindow", "Product Name"))
        self.CategoryLabel.setText(_translate("MainWindow", "Category"))
        self.DetailTextEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sitka Small\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Segoe UI\'; font-size:9pt;\"><br /></p></body></html>"))
        self.DetailLabel.setText(_translate("MainWindow", "Detail"))
        self.PageLabel.setText(_translate("MainWindow", "Add New Product:"))
import Bg_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
